services:
 api:
  image: ${DOCKER_REGISTRY-}api
  build:
   context: .
   dockerfile: API/Dockerfile
 
 frontend:
  image: ${DOCKER_REGISTRY-}frontend
  build:
   context: ./ReactClientApp/app/
   dockerfile: Dockerfile

 db.mysql:
  image: mysql:8.0-debian